/**
 * Generated by tools/web/build.mjs from docs/refusals-live.json. Do not edit by hand.
 *
 * The hosted surface has no database and no filesystem it can trust, so the evidence it
 * serves is compiled in at build time from the same artifact the console renders. A number
 * here that nobody re-derives is a number that goes stale silently, so it is derived.
 */
export interface EvidenceRow {
    readonly caseId: string;
    readonly scenario: string;
    readonly actual: string;
    readonly physicalSends: number;
    readonly txHash: string | null;
    readonly requestId: string | null;
    readonly paymentReference: string | null;
}
export declare const EVIDENCE: {
    readonly generatedAt: string;
    readonly chainId: number;
    readonly totals: Record<string, number>;
    readonly rows: readonly EvidenceRow[];
};
