/**
 * Generated by tools/web/build.mjs from docs/refusals-live.json and
 * docs/evidence/mcp-settlements.json. Do not edit by hand.
 *
 * The hosted surface has no database and no filesystem it can trust, so the evidence it
 * serves is compiled in at build time from the same artifacts the console renders. A number
 * here that nobody re-derives is a number that goes stale silently, so it is derived.
 *
 * Every LIVE settlement belongs here, whichever KeeperHub transport made it: this file once
 * carried the REST rows only, and the hosted verifier answered `paid: false` for all three
 * MCP references because they were not in the table it corroborates against.
 */
export interface EvidenceRow {
    readonly caseId: string;
    readonly scenario: string;
    readonly actual: string;
    /** Which KeeperHub surface dispatched it. "rest" for every row recorded before the MCP run. */
    readonly transport: string;
    readonly physicalSends: number;
    readonly txHash: string | null;
    readonly requestId: string | null;
    readonly paymentReference: string | null;
}
export declare const EVIDENCE: {
    readonly generatedAt: string;
    readonly chainId: number;
    readonly totals: Record<string, number>;
    readonly rows: readonly EvidenceRow[];
};
